// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD81panIGDPA-qMVtZyeuE4ioX1r5SxrB8',
    appId: '1:384305289905:web:6c43567166b13ad6ad6090',
    messagingSenderId: '384305289905',
    projectId: 'quickdrop-cbf49',
    authDomain: 'quickdrop-cbf49.firebaseapp.com',
    storageBucket: 'quickdrop-cbf49.firebasestorage.app',
    measurementId: 'G-2JTTYG59NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjf0K9nQ94IhqeVPt-SgiQGsImZ74D3cs',
    appId: '1:384305289905:android:46e0eaa48b422386ad6090',
    messagingSenderId: '384305289905',
    projectId: 'quickdrop-cbf49',
    storageBucket: 'quickdrop-cbf49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsHfEPq_L2iQInueuzZj1f7Zdr0moXKmU',
    appId: '1:384305289905:ios:97d42431b9517248ad6090',
    messagingSenderId: '384305289905',
    projectId: 'quickdrop-cbf49',
    storageBucket: 'quickdrop-cbf49.firebasestorage.app',
    iosBundleId: 'com.example.quickdrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsHfEPq_L2iQInueuzZj1f7Zdr0moXKmU',
    appId: '1:384305289905:ios:97d42431b9517248ad6090',
    messagingSenderId: '384305289905',
    projectId: 'quickdrop-cbf49',
    storageBucket: 'quickdrop-cbf49.firebasestorage.app',
    iosBundleId: 'com.example.quickdrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD81panIGDPA-qMVtZyeuE4ioX1r5SxrB8',
    appId: '1:384305289905:web:2539911c20e48602ad6090',
    messagingSenderId: '384305289905',
    projectId: 'quickdrop-cbf49',
    authDomain: 'quickdrop-cbf49.firebaseapp.com',
    storageBucket: 'quickdrop-cbf49.firebasestorage.app',
    measurementId: 'G-6P0L2LLD3K',
  );
}
